docs: Add a docs page for RuoYi integration #292
casdoor/casdoor-website pull request #294
Opened 2022-08-18 08:38 UTC by jakiuncle

2022-08-18 09:01 UTC, hsluoyz commented
@Selflocking @leo220yuyaodog plz review

2022-08-18 10:04 UTC, Selflocking commented on docs/integration/RuoYi.md
> +```SpringBoot
plz use `java`

2022-08-18 10:04 UTC, Selflocking commented on docs/integration/RuoYi.md
> +```SpringBoot
plz use `java`

2022-08-18 10:04 UTC, Selflocking commented on docs/integration/RuoYi.md
> +```SpringBoot
plz use `java`

2022-08-18 10:04 UTC, Selflocking commented on docs/integration/RuoYi.md
> +```SpringBoot
plz use `java`

2022-08-18 10:04 UTC, Selflocking commented on docs/integration/RuoYi.md
> +}
```js
created() {
    let url = window.document.location.href//get url
    let u = new URL(url);
    this.loginForm.code = u.searchParams.get('code')//get code and state
    this.loginForm.state = u.searchParams.get('state')
    if(this.loginForm.code!=null&&this.loginForm.state!=null){//if code and state is null,execute handleLogin
      this.handleLogin()
    }  
}
```

This code also appears [above](https://github.com/casdoor/casdoor-website/pull/294/files#diff-e05b0df1e14be4a7583ad21dc87743ad3bd81f8a5b3f0f132b6272a311b05f74R38), so is it vue code or SpringBoot code?

2022-08-18 12:28 UTC, leo220yuyaodog requested changes

2022-08-18 13:57 UTC, jakiuncle commented
@Selflocking @leo220yuyaodog plz review

2022-08-18 14:16 UTC, leo220yuyaodog commented on docs/integration/RuoYi.md
> +We can use font-end sdk,take vue-sdk as a exmaple here. After you init vue-sdk,you can get casdoor login page url by getSigninUrl().
vue-sdk, you

2022-08-18 14:16 UTC, leo220yuyaodog commented on docs/integration/RuoYi.md
> +You also should configure organization, role, permissions, modle, application, Synchronizer, you also can refer to [casdoor](https://door.casdoor.com/login).
In this section, it is better to show an example for user to follow and config.
And refer to specific docunment, like [application](https://casdoor.org/docs/application/config), [Synchronizer](https://casdoor.org/docs/syncer/overview).

2022-08-18 14:18 UTC, leo220yuyaodog commented on docs/integration/RuoYi.md
> +You also should configure organization, role, permissions, modle, application, Synchronizer, you also can refer to [casdoor](https://door.casdoor.com/login).
@jakiuncle plz improve this section.

2022-08-18 14:20 UTC, Selflocking requested changes

2022-08-18 14:20 UTC, Selflocking commented on docs/integration/RuoYi.md
> +You also should configure organization, role, permissions, modle, application, Synchronizer, you also can refer to [casdoor](https://door.casdoor.com/login).
typo?
```suggestion
You also should configure organization, role, permissions, model, application, Synchronizer, you also can refer to [casdoor](https://door.casdoor.com/login).
```

2022-08-18 14:24 UTC, Selflocking commented
plz edit `docusaurus.config.js`

change 
```js
      additionalLanguages: ['nginx'],
```
to
```js
      additionalLanguages: ['nginx', 'java'],
```

2022-08-18 14:36 UTC, Selflocking requested changes

2022-08-18 14:36 UTC, Selflocking commented on docs/integration/RuoYi.md
> +We can use font-end sdk,take vue-sdk as a exmaple here. After you init vue-sdk,you can get casdoor login page url by getSigninUrl().
typo
```suggestion
We can use front-end sdk,take vue-sdk as a exmaple here. After you init vue-sdk,you can get casdoor login page url by getSigninUrl().
```

2022-08-18 14:36 UTC, Selflocking commented on docs/integration/RuoYi.md
> +### 4.1 Accept the code and state which return by font-end
typo
```suggestion
### 4.1 Accept the code and state which return by front-end
```

2022-08-18 14:36 UTC, Selflocking commented on docs/integration/RuoYi.md
> +### 5.1 font-end
typo
```suggestion
### 5.1 front-end 
```

2022-08-18 14:36 UTC, Selflocking commented on docs/integration/RuoYi.md
> +3. After we deployed casdoor, we should change font-end. We should close RuoYi check code
typo
```suggestion
3. After we deployed casdoor, we should change front-end. We should close RuoYi check code 
```

2022-08-18 15:03 UTC, Selflocking requested changes

2022-08-19 02:21 UTC, jakiuncle commented
@Selflocking @leo220yuyaodog  Plz review agian.Hhank you.

2022-08-19 03:08 UTC, leo220yuyaodog approved these changes

2022-08-19 04:01 UTC, hsluoyz commented
@Selflocking

2022-08-20 06:59 UTC, Selflocking approved these changes

2022-08-20 13:21 UTC, merged