docs: add login ui customization tutorial
casdoor/casdoor-website pull request #379
Opened 2022-10-24 11:12 UTC by leo220yuyaodog

close: #375 

Signed-off-by: magicwind <2814461814@qq.com>

2022-10-24 14:13 UTC, leo220yuyaodog commented
@Selflocking @yoyo314 Can you help me with review? Thanks.

2022-10-25 00:51 UTC, Selflocking requested changes

2022-10-25 00:51 UTC, Selflocking commented on docs/application/ui-customization.md
> +Now the login page is much prettier than the beginning.  We also provider three buttons for you to decide the position of the panel.
```suggestion
Now the login page is much prettier than the beginning. We also provide three buttons for you to decide the position of the panel.
```

2022-10-25 00:51 UTC, Selflocking commented on docs/application/ui-customization.md
> +
plz leave only one blank line.

2022-10-25 00:51 UTC, Selflocking commented on docs/application/ui-customization.md
> +You will see now how you can enable a side panel and custom the style.
```suggestion
You will see now how you can enable a side panel and custom the style.
```

2022-10-25 00:51 UTC, Selflocking commented on docs/application/ui-customization.md
> +Just copy and paste.
```suggestion
Just copy and paste.
```

2022-10-25 00:51 UTC, Selflocking commented on docs/application/ui-customization.md
> +Let's see the effect. The side panel with a logo and image is shown, but the result didn't see well.
```suggestion
Let's see the effect. The side panel with a logo and image is shown, but the result didn't see well.
```

2022-10-25 00:51 UTC, Selflocking commented on docs/application/ui-customization.md
> +The final code is as follows.
```suggestion
The final code is as follows.
```

2022-10-25 01:11 UTC, Selflocking requested changes

2022-10-25 02:02 UTC, merged