feat: Add Jira docs
casdoor/casdoor-website pull request #385
Opened 2022-11-04 11:56 UTC by jakiuncle

feat: Add Jira docs

2022-11-04 11:59 UTC, Selflocking commented
![image](https://user-images.githubusercontent.com/53544726/199967534-b8581ff0-b478-4004-a05a-07c3112ce072.png)

2022-11-04 12:39 UTC, leo220yuyaodog requested changes

2022-11-04 12:39 UTC, leo220yuyaodog commented on docs/integration/java/jira oidc.md
> +3. My use default pord so my CASDOOR_HOSTNAME = 'http://localhost:8000'
```suggestion
3. CASDOOR_HOSTNAME = 'http://localhost:8000'. When deploy Casdoor in `prod` mode. See [producation mode](https://casdoor.org/docs/basic/server-installation#production-mode).
```

2022-11-04 12:46 UTC, leo220yuyaodog commented on docs/integration/java/jira oidc.md
> +     - `Token server url`: **http://`CASDOOR_HOSTNAME`/api/login/oauth/access_token**
Too much indentation. It's not very nice here.

![image](https://user-images.githubusercontent.com/71440988/199975485-24072f56-8420-48a9-a65b-d904ddaebc7c.png)

2022-11-04 12:53 UTC, Selflocking commented
One more thing: change your pr name to `docs: add Jira docs`.
https://casdoor.org/docs/contributing#semantic-prs

2022-11-04 13:16 UTC, hsluoyz commented on sidebars.js
> +            "integration/java/jira oidc",
@jakiuncle use `jira` directly as name

2022-11-05 01:06 UTC, Selflocking approved these changes

2022-11-05 02:47 UTC, leo220yuyaodog requested changes

2022-11-05 02:47 UTC, leo220yuyaodog commented on docs/integration/java/jira.md
> +3. I use default prod so my CASDOOR_HOSTNAME = 'http://localhost:8000'.When deploy Casdoor in `prod` mode. See [production mode](https://casdoor.org/docs/basic/server-installation#production-mode).
```suggestion
3. You can set CASDOOR_HOSTNAME = `http://localhost:8000`. When deploy Casdoor in `prod` mode. See [production mode](https://casdoor.org/docs/basic/server-installation#production-mode).
```

2022-11-05 04:01 UTC, leo220yuyaodog approved these changes

2022-11-05 14:13 UTC, merged