docs: add iotdb-web-website docs
casdoor/casdoor-website pull request #443
Opened 2023-03-25 13:02 UTC by jakiuncle

docs: add iotdb-web-website docs

2023-03-25 15:27 UTC, Selflocking approved these changes

2023-03-26 01:43 UTC, leo220yuyaodog requested changes

2023-03-26 01:43 UTC, leo220yuyaodog commented on docs/integration/java/iotdb.md
> +### step2.1 you should create an organization
```suggestion
### 2.1 you should create an organization
```

2023-03-26 01:43 UTC, leo220yuyaodog commented on docs/integration/java/iotdb.md
> +### step2.2 you should create an application
```suggestion
### 2.2 you should create an application
```

2023-03-26 08:30 UTC, leo220yuyaodog approved these changes

2023-03-26 09:13 UTC, merged