Support CloudFoundry authentication with Casdoor (#1807)
casdoor/casdoor-website pull request #477
Opened 2023-05-12 15:21 UTC by RanTao123

2023-05-13 07:08 UTC, Selflocking requested changes

2023-05-13 07:08 UTC, Selflocking commented on docs/integration/Haskell/Hasura.md
> +metaDescription: "Learn how to integrate Casdoor with Hasura to secure your applications using JWT"
should be like:
```md
---
title: Title
description: description
keywords: [keyword1, keyword2]
authors: [GitHub username]
---
```

2023-05-13 07:08 UTC, Selflocking commented on docs/integration/java/CloudFoundry.md
> +metaDescription: "Learn how to integrate Casdoor with CloudFoundry to secure your applications using JWT"
should be like:
```md
---
title: Title
description: description
keywords: [keyword1, keyword2]
authors: [GitHub username]
---
```

2023-05-13 17:59 UTC, closed without merging

2023-05-14 00:37 UTC, hsluoyz commented
Replaced by: https://github.com/casdoor/casdoor-website/pull/479