docs: add NGINX Plus
casdoor/casdoor-website pull request #523
Opened 2023-07-20 17:06 UTC by SkipperQ

2023-07-20 17:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/casdoor/casdoor-website?pullRequest=523) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/casdoor/casdoor-website?pullRequest=523) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/casdoor/casdoor-website?pullRequest=523) it.</sub>

2023-07-21 14:00 UTC, hsluoyz commented
@Selflocking

2023-07-21 15:03 UTC, Selflocking commented
![image](https://github.com/casdoor/casdoor-website/assets/53544726/81c56526-38a4-4334-99d9-bde129cc8028)

There should be no spaces in the file name. Please rename to `NGINX-Plus.md`

2023-07-21 15:06 UTC, Selflocking requested changes

2023-07-21 15:06 UTC, Selflocking commented on docs/integration/C++/NGINX Plus.md
> +# NGINX Plus
![image](https://github.com/casdoor/casdoor-website/assets/53544726/f0d20675-b898-4e38-bf71-cf4700084cd4)

2023-07-21 15:06 UTC, Selflocking commented on docs/integration/C++/NGINX Plus.md
> +    ```
```suggestion
    ```bash
```

2023-07-21 15:06 UTC, Selflocking commented on docs/integration/C++/NGINX Plus.md
> +    ```
```suggestion
    ```bash
```

2023-07-21 15:41 UTC, Selflocking commented
@SkipperQ You can megre this PR(https://github.com/SkipperQ/casdoor-website/pull/2) to pass these checks.
![image](https://github.com/casdoor/casdoor-website/assets/53544726/1d30d784-9eef-465e-8801-e339ac394e83)

2023-07-22 04:33 UTC, Selflocking commented
https://github.com/SkipperQ/casdoor-website/pull/3

2023-07-22 05:39 UTC, Selflocking commented
@SkipperQ please sign our [Contributor License Agreement](https://cla-assistant.io/casdoor/casdoor-website?pullRequest=523)

![image](https://github.com/casdoor/casdoor-website/assets/53544726/e11d1807-1978-465b-894f-6ae91f8ed7a4)

2023-07-22 06:30 UTC, merged